export const MODULES = {
  PATIENT: 'PATIENTS',
  DRUG: 'DRUGS',
  AGENDA: 'AGENDA',
  TOOLS: 'TOOLS'
}

export const PATIENT_SECTIONS = {
  IDENTIFICATION: 'IDENTIFICATION',
  MEDICAL_RECORDS: 'MEDICAL_RECORDS',
  MEDICAL_RECORDS_PHOTOS: 'MEDICAL_RECORDS_PHOTOS',
  REPORT: 'REPORT'
}

export const DRUG_SECTIONS = {
  FORM: 'FORM'
}

export const DEFAULT_SECTION_PER_MODULE = {
  [MODULES.PATIENT]: PATIENT_SECTIONS.IDENTIFICATION,
  [MODULES.DRUG]: DRUG_SECTIONS.FORM
}
