export const MODULES = {
  SESSION: 'SESSION',
  ADMIN: 'ADMIN',
  PATIENT: 'PATIENTS',
  DRUG: 'DRUGS',
  AGENDA: 'AGENDA',
  TOOLS: 'TOOLS'
}

export const SESSION_SECTIONS = {
  LOGIN: 'LOGIN'
}

export const ADMIN_SECTIONS = {
  USERS_MANAGEMENT: 'USERS_MANAGEMENT'
}

export const PATIENT_SECTIONS = {
  IDENTIFICATION: 'IDENTIFICATION',
  MEDICAL_RECORDS: 'MEDICAL_RECORDS',
  MEDICAL_RECORDS_PHOTOS: 'MEDICAL_RECORDS_PHOTOS',
  PRESCRIPTION: 'PRESCRIPTION'
}

export const DRUG_SECTIONS = {
  FORM: 'FORM'
}

export const AGENDA_SECTIONS = {
  APPOINTMENTS: 'APPOINTMENTS'
}

export const DEFAULT_SECTION_PER_MODULE = {
  [MODULES.SESSION]: SESSION_SECTIONS.LOGIN,
  [MODULES.ADMIN]: ADMIN_SECTIONS.USERS_MANAGEMENT,
  [MODULES.PATIENT]: PATIENT_SECTIONS.IDENTIFICATION,
  [MODULES.DRUG]: DRUG_SECTIONS.FORM,
  [MODULES.AGENDA]: AGENDA_SECTIONS.APPOINTMENTS
}
